// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
int dirt;
int width;
StructuredBuffer<int> tile_map;
RWTexture2D<float4> result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int val = 0;
    if (tile_map[id.x + id.y * width] == dirt) val = 1;

    result[id.xy] = float4(val, val, val, 0.0);
}
